# Zero-Trust API Communication Policies
policy_version: 1.1
max_request_size: 1048576  # 1MB in bytes
policies:
  - name: graphql_depth_control
    description: Prevent nested query attacks
    rules:
      - max_depth: 6
        action: reject
      - query_complexity: 1000
        action: throttle

  - name: parameter_sanitization
    description: Prevent injection attacks
    rules:
      - pattern: '[;\\]'
        fields: [query, body]
        action: sanitize

  - name: behavioral_baseline
    description: AI-driven anomaly detection
    metrics:
      - request_frequency
      - parameter_variation
      - response_size
    training_window: 14d
    max_parameters: 100  # Maximum number of parameters allowed in a request
    max_requests_per_minute: 1000  # Maximum requests per minute before considering anomalous
    anomaly_thresholds:
      request_frequency: 0.95  # 95th percentile threshold
      parameter_variation: 0.90  # 90th percentile threshold
      response_size: 0.95  # 95th percentile threshold
    alert_on_anomaly: true  # Enable alerting
    self_healing_enabled: true  # Enable automatic mitigation

  - name: self_healing
    actions:
      - type: circuit_breaker
        threshold: 500ms  # Response time threshold
        reset_time: 30s  # Time to wait before resetting circuit breaker
      - type: rate_limit
        requests_per_minute: 1000
        burst_capacity: 50
      - type: schema_validation
        strict: true
        max_depth: 10

  - name: rate_limit
    description: Global API rate limiting
    rules:
      - max_requests_per_minute: 1000
        action: throttle
      - burst_capacity: 50
        action: reject

  - name: jwt_validation
    description: Validate JWT tokens
    rules:
      - required_claims: ["sub", "iss", "exp"]
        algorithms: ["RS256"]
        clock_skew: 30  # seconds
        issuer: "fastapi-security-gateway"
        audience: "protected-api"

jwt:
  secret_env: JWT_SECRET
  refresh_window: 300  # 5 minutes before expiry
  token_expiry: 3600  # 1 hour

# Monitoring and alerting settings
monitoring:
  log_level: INFO
  metrics_enabled: true
  alert_threshold: 80  # CPU/Memory threshold for alerts
  alert_channels:
    - type: email
      enabled: false
      recipients: ["admin@yourdomain.com"]
    - type: slack
      enabled: false
      webhook_url: "https://hooks.slack.com/services/your/webhook/url"

# CORS settings
cors:
  allowed_origins: ["http://localhost:3000", "https://yourdomain.com"]
  allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowed_headers: ["Authorization", "Content-Type"]
  expose_headers: ["X-Rate-Limit"]
  max_age: 600  # 10 minutes