policies:
  behavioral_baseline:
    training_window: "14d"
    max_requests_per_minute: 1000
    max_parameters: 100
  rate_limiting:
    enabled: true
    requests_per_minute: 100
    burst_size: 20
  security:
    max_request_size: 1048576  # 1MB
    allowed_origins: ["*"]
    authentication: "required"
  monitoring:
    log_level: "INFO"
    metrics_enabled: true
    alert_threshold: 80